# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Class
    url: /#papers
    weight: 11
  - name: Club
    url: /#talks
    weight: 12
  - name: Experence
    url: experience/
    weight: 20
  - name: Projects
    weight: 30
    hasChildren: true
  - parent: Projects
    name: Projects 1
    url: project1/
    weight: 1
  - parent: Projects
    name: Projects 2
    url: project2/
    weight: 2
  - name: Location
    url: location/
    weight: 30